---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
      namespace: hass 
      ha_url: http://192.168.1.***:8123  # Server IP
      delay: 0
      token: eyJh # Long lived Token
   
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard: