mqtt:
    sensor:
        - name: "PWM Sensor"
          state_topic: "PWM_Sensor"
          unit_of_measurement: "%"

        - name: "Gas price"
          state_topic: "Gas_Price"
          unit_of_measurement: "€"

        - name: "Energy Price"
          state_topic: "Energy_Price"
          unit_of_measurement: "€/MWh"

        - name: "Mode"
          state_topic: "Mode"