alias: MQTT Mode
description: Sends mode to MQTT
trigger:
  - platform: state
    entity_id:
      - sensor.energyprice
      - sensor.gasprice
      - input_select.mode
condition: []
action:
  - if:
      - condition: state
        entity_id: input_select.mode
        state: Automatic
    then:
      - if:
          - condition: template
            value_template: >-
              (float(states('sensor.energyprice'))*0.95*0.207) >
              (float(states('sensor.gasprice')*0.75))
        then:
          - service: mqtt.publish
            data:
              qos: "0"
              retain: true
              topic: Mode
              payload: "0"
        else:
          - service: mqtt.publish
            data:
              qos: "0"
              retain: true
              topic: Mode
              payload: "1"
    else:
      - if:
          - condition: state
            entity_id: input_select.mode
            state: Sell
        then:
          - service: mqtt.publish
            data:
              qos: "0"
              retain: true
              topic: Mode
              payload: "0"
        else:
          - service: mqtt.publish
            data:
              qos: "0"
              retain: true
              topic: Mode
              payload: "1"
mode: single
